### PR TITLE
Affine backend modifications

### PR DESCRIPTION
**Pull request by phschon**
This request includes the following changes as noted in #3 :

- added affine curves
- curve interface contains all basic functions
- curve interface is used throughout the code as basic data type
- added affinecurve interface
- added calculator config flag for affine curves

Until now, CurveAffine and CurvePwAffine are nearly empty and identical, they can be modified as needed for future purposes.
All tests are green.

The following UML diagram shows the new hierarchy.

screenshot

### CODE REVIEW

**Comment by sbondorf** [comment]
@phschon Could please you check the TODO comment in PmooAnalysis.java that state "TODO Actually needs to be an affine curve", run the test and report back?

**Comment by sbondorf** [comment]
I think this refactoring work should be merged into the v2.5 branch instead of master, probably before #2 gets pulled in.

**Comment by phschon** [comment]
Short update: the tests do NOT work, when AffineCurves are used. ATM I am looking into it.

**Comment by NetCal** [comment]
I somehow managed to merge this pull request into branch v2.5.

**Pull request closed without merging**
