### PR TITLE
Moving integration tests to separate modul.

### PR DESCRIPTION
**Pull request by matyesz**

### CODE REVIEW

**Comment by matyesz** [comment]
Merged with changes in master.

**Comment by sbondorf** [comment]
I tried building the parent (meta) project but failed so far. Can we add some more Howto material specific to our project to the Changelog / README.md?
* The paths to parents and modules are hardcoded and thus should not be changed on a developer's local machine.
* I still get this Maven error:
[FATAL] Non-resolvable parent POM for de.uni_kl.cs.discodnc:DiscoDNC_tests:[unknown-version]: Failure to find de.uni_kl.cs.discodnc:DiscoDNC_meta:pom:2.5.0 in https://repo.maven.apache.org/maven2

**Comment by matyesz** [comment]
Unfortunatelly maven has some restrictions with multimodule projects. If you use the default values then parent pom must be in a folder where all modules are subfolders or you must hardcode the path. We never had problems with this in business as usually people keep projects in the same parent folder and jenkins is also able to handle it. The reason for the error is that you have to start the build from the meta, once you do an install from the meta, you will be able to individual builds. Separate modules do not know about the other module, they try to find them in the repo.

**Comment by sbondorf** [comment]
The individual pull requests in the different projects all seem fine, but complexity increased considerably in comparison to the single-project master branch. Thus, I feel we need to provide an easy to follow guide explaining how the modular project works, explaining requirements like the common parent folder or folder naming conventions. CONTRIBUTING.md might be the right place for that.

**Comment by matyesz** [comment]
Will add CONTRIBUTING.md to the meta project. I wanted to add all these infos to the meta project README.md so it will immediatelly visible on the github web page.

**Pull request merged**
