### PR TITLE
Disco dnc refactoring

### PR DESCRIPTION
**Pull request by matyesz**
Please check whether separation is OK.

### CODE REVIEW

**Comment by matyesz** [comment]
MPA_RTC part submitted to: https://github.com/matyesz/DiscoDNC_RTC/tree/master/DiscoDNC_RTC

**Comment by NetCal** [comment]
Ok, this is the first round of my thoughts, in particular how I see the changes in the big DiscoDNC picture: The role of CalculatorConfig.java changes significantly.

Before, it only stored values and the respective classes (Num, Curve, etc.) dispatched to the actual implementations. Thus perfect knowledge was necessary, the MPA RTC toolbox had to be a compile-time dependency for the provided wrappers.

The changes depart from this dispatching in the respective classes themselves. Dispatching is to Curve and MinPlus is done by CalculatorConfig.java. To do so, an inner interface for the curve backend is defined. Curve backend being a Curve implementation (currently pwl, DNC or RTC) and a MinPlus implementation that can work on these curves.

This makes CalculatorConfig.java more than a dumb config file. It rather takes a superordinate role -- similar to AnalysisConfig being superordinate to the analyses and the arrival boundings.  Therefore, I suggest the following:
* Move it to package de.uni_kl.cs.discodnc
* Rename it to Calculator.java
* Rename the inner interface from CurveImpl to CurveBackend and make it an interface in de.uni_kl.cs.discodnc
* Move de.uni_kl.cs.discodnc.nc.CurveImpl_DNC to de.uni_kl.cs.discodnc.CurveBackend_DNC
  - CurveBackend_DNC: rename getCurve() to get getCurveFactory()

Moreover, can we include an instance of LinearSegment instead of the the two methods?
@phschon The DNC curves can work with the MPA RTC LinearSegment wrappers as they implement our interface and map the operations to the RTC ones, right? Then, we code split out could provide an hybrid CurveBackend in addition to the current de.uni_kl.cs.discodnc.nc.CurveImpl_MPA_RTC

The obvious further extension to this work is to include different implementations for basic bounds (delay, backlog, output) in the CurveBackend. The dispatching code is currently in comments in de.uni_kl.cs.discodnc.nc.bounds.Bound.

**Comment by matyesz** [comment]
Agreed. CalculatorConfig will become a dispatcher between Curve and MinPlus implementation that are bound to the extensible enum (DNC and RTC) that can be extended with other implementations later. Actually although they are enums we rather use them as singletons (Effective Java r3.0) in the project.

I will do the suggested modifications.

**Comment by matyesz** [comment]
@phschon The DNC curves can work with the MPA RTC LinearSegment wrappers as they implement our interface and map the operations to the RTC ones, right? Then, we code split out could provide an hybrid CurveBackend in addition to the current de.uni_kl.cs.discodnc.nc.CurveImpl_MPA_RTC

Here I would do some refactoring too. If they can be used in hybrid mode (CurveBackend_DNC and LinearSegment_MPA_RTC) then LinearSegment should come from Configurator similiar to Curve and let users configure LinearSegment too. 
@sbondorf: Is hybrid mode a valid use-case?

**Comment by sbondorf** [comment]
I am in favor of treating LinearSegment like Curve(PwAffine) and MinPlus by adding it to CurveBackend and thus to Calculator. To me, this seems to complete this work.

We once profiled method calls of both curve backends. Turns out the DNC calls to Num's createZero() consume most time. We have not tested the hybrid solution but it could speed up the computations. Overall, I think showing the hybrid solution is more of academic interest.

**Comment by NetCal** [comment]
As changes are quite fundamental, I created a v2.5 branch for it and other work to be added for this next version.
Could you change the target of your pull request?

**Comment by matyesz** [comment]
Moved to branch v2.5. Once we have the project DiscoDNC_RTC in NetCal repo, we can add the hybrid CurveBackend to that or we can decide to create a separate extension for that too (first one is somehow logical as we do not introudce new calculation method just mix it second one is a clear solution as we extend both functionality with a new approach).

**Comment by sbondorf** [comment]
Right, the extension needs to go into a separate repository. Another reason can be found in Maven's Guide to uploading artifacts to the Central Repository [1]. It states the requirement to "only depend on other files already released and available in the repository."

For the overall changes currently queued in pull requests, I think merging #5 first saves us from some hassle. Other than this "soft dependency", I do not see any reason not to merge into the v2.5 branch and letting the code further mature there.

[1] https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by matyesz** [comment]
I will wait till #3 gets fully resolved and commited to merge only once.

**Pull request merged**
